#!/usr/bin/env bash
#Auditing DNS records

function audit_subdomain (
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomain=("www" "lb-01" "web-01" "web-02")
	else
		subdomain=("$subdomain")
	fi

	for sub in "${subdomain[0]}"; do
		record_type"$(dig "$sub.$domain" | awk '/answer section/ { getline; print $4}')
		destination"$(dig "$sub.$domain" | awk '/answer section/ { getline; print $5}')
		echo "The subdomain $sub is a $record_type record and points to $destination"
	done
)
audit_subdomain "$1" "$2"
